id: PDFA09FD6
initial_creation_type: ocr
source_metadata:
  volumes:
    b33645d75b3f42d5ba6a12092e9fec09:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: གཙུག་ཏོར་དྲི་མེད་ཀྱི་གཟུངས་ཆོག།
      total_pages: 1044
      volume_number: 38
